
### 
GET http://localhost:3000/api/geotags HTTP/1.1
###
POST http://localhost:3000/api/geotags HTTP/1.1
content-type: application/json

{
    "name": "Berlin", 
    "latitude": 52.5200, 
    "longitude": 13.4050, 
    "hashtag": "#berlin"
}

### 
GET http://localhost:3000/api/geotags/1 HTTP/1.1

### 
PUT http://localhost:3000/api/geotags/11 HTTP/1.1 
Content-Type: application/json

{
    "name": "Berlin Updated", "latitude": 52.5300, "longitude": 13.4050, "hashtag": "#newBerlin"
}

### search for berlin
GET http://localhost:3000/api/geotags?searchTerm=berlin&latitude=52.5200&longitude=13.4050 

### search campus
GET http://localhost:3000/api/geotags?latitude=48.91614&longitude=8.38086&searchTerm=cam


### 
DELETE http://localhost:3000/api/geotags/1 HTTP/1.1
